# Datasource
quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=postgres
quarkus.datasource.password=postgres
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5434/postgres
quarkus.hibernate-orm.mapping.format.global=ignore

# Hibernate ORM
quarkus.hibernate-orm.database.generation=none
quarkus.hibernate-orm.physical-naming-strategy=org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy

# Liquibase
quarkus.liquibase.change-log=db/changelog/db.changelog-master.xml
quarkus.liquibase.migrate-at-start=true

# CORS
#quarkus.http.cors=true
#quarkus.http.cors.origins=http://localhost:3000
#quarkus.http.cors.methods=GET,POST,PUT,PATCH,DELETE,OPTIONS
#quarkus.http.cors.headers=Content-Type,Authorization
#quarkus.http.cors.exposed-headers=Content-Type,Authorization

# SmallRye JWT
quarkus.smallrye-jwt.enabled=true

# OpenAPI / Swagger
quarkus.smallrye-openapi.path=/openapi
quarkus.smallrye-openapi.info-title=English Learning API
quarkus.smallrye-openapi.info-version=1.0.0
quarkus.swagger-ui.always-include=true

# Keep only these for verification:
mp.jwt.verify.issuer=english-learning-api
#smallrye.jwt.sign.key.location=privatekey.pem

mp.jwt.verify.publickey.location=${PUBLIC_KEY_PATH}
smallrye.jwt.sign.key.location=${PRIVATE_KEY_PATH}

# Application JWT config
app.jwt.expiration-seconds=86400

# General Quarkus logging
quarkus.log.console.enable=true
quarkus.log.console.level=DEBUG
quarkus.log.level=INFO

# JWT logging
quarkus.log.category."io.smallrye.jwt".level=DEBUG
quarkus.log.category."org.jose4j".level=DEBUG